version: '3.4'

services:
  localdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
  set-demo:
    image: ${DOCKER_REGISTRY-}set-demo
    build:
      context: ../
      dockerfile: Demo/Dockerfile